// Data-content localization.
//
// All static game data (cards, enemies, relics, tiles, materials, buildings,
// passives) ships in English inside src/data/json/*.json. Those JSON imports
// are module singletons shared by every consumer (DataLoader, LootGenerator,
// MetaProgressionSystem, HeroStatsResolver, ...). We localize the player-facing
// `name`/`description` fields by MUTATING those singletons in place, so every
// reader sees the active-locale text without any call-site changes.
//
// English is the canonical base: the first time applyDataLocale runs we snapshot
// every original string, so switching back to 'en' restores it exactly and the
// overlays never compound. Card *descriptions* are intentionally NOT touched
// here — they are generated by CardText.formatCardDescription(), which is itself
// locale-aware. Only card *names* are overlaid.

import type { Locale } from './i18n';
import { localizeElements } from '../systems/ElementSystem';

import cardsData from '../data/json/cards.json';
import enemiesData from '../data/json/enemies.json';
import tilesData from '../data/json/tiles.json';
import relicsData from '../data/json/relics.json';
import materialsData from '../data/json/materials.json';
import buildingsData from '../data/json/buildings.json';
import passivesData from '../data/json/passives.json';
import warriorPassivesData from '../data/json/warrior-passives.json';
import magePassivesData from '../data/json/mage-passives.json';

import cardsPt from './data/cards.pt-br.json';
import enemiesPt from './data/enemies.pt-br.json';
import relicsPt from './data/relics.pt-br.json';
import tilesPt from './data/tiles.pt-br.json';
import materialsPt from './data/materials.pt-br.json';
import buildingsPt from './data/buildings.pt-br.json';
import passivesPt from './data/passives.pt-br.json';
import warriorPassivesPt from './data/warrior-passives.pt-br.json';
import magePassivesPt from './data/mage-passives.pt-br.json';

/** A single localizable entity's overlay fields. */
interface Tr {
  name?: string;
  description?: string;
  /** Per-tier descriptions (buildings), index-aligned with the tiers array. */
  tiers?: string[];
}
type Overlay = Record<string, Tr>;

const PT_OVERLAYS = {
  cards: cardsPt as Overlay,
  enemies: enemiesPt as Overlay,
  relics: relicsPt as Overlay,
  tiles: tilesPt as Overlay,
  materials: materialsPt as Overlay,
  buildings: buildingsPt as Overlay,
  passives: passivesPt as Overlay,
  warriorPassives: warriorPassivesPt as Overlay,
  magePassives: magePassivesPt as Overlay,
};

// ── English-base snapshot (captured once) ──────────────────────────────────
interface BaseSnap {
  name?: string;
  description?: string;
  tiers?: (string | undefined)[];
}
const baseByKey = new Map<string, BaseSnap>();
let baseCaptured = false;

/** A node with optional name/description we localize in place. */
interface LocNode {
  name?: string;
  description?: string;
  tiers?: { description?: string }[];
}

/** Every (overlay-namespace, id, node) we localize, computed once per call. */
type Target = { ns: keyof typeof PT_OVERLAYS; id: string; node: LocNode };

function collectTargets(): Target[] {
  const out: Target[] = [];
  const arr = (v: unknown): any[] => (Array.isArray(v) ? v : []);

  const cards = arr((cardsData as any).cards);
  for (const c of cards) out.push({ ns: 'cards', id: c.id, node: c });

  for (const e of arr(enemiesData)) out.push({ ns: 'enemies', id: e.id, node: e });
  for (const r of arr(relicsData)) out.push({ ns: 'relics', id: r.id, node: r });
  for (const t of arr(tilesData)) out.push({ ns: 'tiles', id: t.type, node: t });

  for (const m of arr((materialsData as any).materials)) out.push({ ns: 'materials', id: m.id, node: m });

  const buildings = buildingsData as Record<string, LocNode>;
  for (const id of Object.keys(buildings)) out.push({ ns: 'buildings', id, node: buildings[id] });

  const passives = passivesData as Record<string, any[]>;
  for (const cls of Object.keys(passives)) {
    for (const p of arr(passives[cls])) out.push({ ns: 'passives', id: p.id, node: p });
  }

  for (const p of arr(warriorPassivesData)) out.push({ ns: 'warriorPassives', id: p.id, node: p });
  for (const p of arr(magePassivesData)) out.push({ ns: 'magePassives', id: p.id, node: p });

  return out;
}

function captureBase(): void {
  if (baseCaptured) return;
  for (const { ns, id, node } of collectTargets()) {
    baseByKey.set(`${ns}:${id}`, {
      name: node.name,
      description: node.description,
      tiers: node.tiers?.map((tr) => tr.description),
    });
  }
  baseCaptured = true;
}

let appliedLocale: Locale | null = null;

/**
 * Mutate every localizable data singleton to `locale`. Idempotent: re-applying
 * the same locale is a no-op, and switching back to English restores the
 * snapshotted originals. Safe to call before scenes mount (Boot) and again on a
 * runtime language switch.
 */
export function applyDataLocale(locale: Locale): void {
  captureBase();
  if (appliedLocale === locale) return;

  // Element display names + identity tooltips (mutated in place in their own module).
  localizeElements(locale);

  for (const { ns, id, node } of collectTargets()) {
    const base = baseByKey.get(`${ns}:${id}`);
    if (!base) continue;
    const tr = locale === 'en' ? undefined : PT_OVERLAYS[ns][id];

    // name
    const nm = tr?.name ?? base.name;
    if (nm !== undefined) node.name = nm;

    // description
    const desc = tr?.description ?? base.description;
    if (desc !== undefined) node.description = desc;

    // building tier descriptions (index-aligned)
    if (node.tiers && base.tiers) {
      node.tiers.forEach((tier, i) => {
        const v = tr?.tiers?.[i] ?? base.tiers?.[i];
        if (v !== undefined) tier.description = v;
      });
    }
  }

  appliedLocale = locale;
}
